name: get_popular_articles
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  riverpod_generator: ^2.2.1
  riverpod_annotation: ^2.1.1
  freezed: ^2.3.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  dio: ^5.1.1
  url_launcher: ^6.1.10
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.1
  json_serializable: ^6.6.2
  retrofit_generator: ^6.0.0+3

flutter:
  uses-material-design: true